# -*- coding: utf-8 -*-
"""email-spam-detection-98-accuracy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6rcOm0-Ri3nppHyXJCm36o1EcVqAjRC

<img src="https://helpemailmarketing.com/wp-content/uploads/2019/12/spam-filter-34101a1e6c494d44aa1b6d10302537da.jpg"  style='width:1000px'>
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

data=pd.read_csv('/content/mail_data (2).csv', encoding='ISO-8859-1')
data

data.columns

data.info()

"""**Dropped The Column Unnamed: 0**"""

data.isna().sum()

data['Spam']=data['Category'].apply(lambda x:1 if x=='spam' else 0)
data.head(5)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data.Message,data.Spam,test_size=0.25)

#CounterVectorizer Convert the text into matrics
from sklearn.feature_extraction.text import CountVectorizer

"""**Naive Bayes Have three Classifier(Bernouli,Multinominal,Gaussian)
Here I use Multinominal Bayes Because here data in a discrete form
discrete data(e.g movie ratings ranging  1 to 5 as each rating will have certain frequency to represent)**
"""

from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

"""# Tarining The Model"""

clf.fit(X_train,y_train)

"""**Here I given Two email Two detect 1st One is looking good and the other one looking spam**"""

emails=[
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

clf.predict(emails)

email_1 = ['Sounds great! Are you home now?']

clf.predict(email_1)

email_2 = ['adult club offers free membership instant access to all sites now your user name and password is us...']

clf.predict(email_2)

"""# Prediction Of Model"""

clf.score(X_test,y_test)